lib/cinema_web/router.ex
defmodule CinemaWeb.Router do
  use CinemaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CinemaWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "videos", VideoController, only: [:index, :new, :create]
  end

  scope "/api/v1", CinemaWeb do
    pipe_through :api
  
    resources "videos", VideoAPIController, only: [:create, :show, :index]
  end
end

lib/cinema/application.ex
defmodule Cinema.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Cinema.Repo, []),
      # Start the endpoint when the application starts
      supervisor(CinemaWeb.Endpoint, []),
      # Start your own worker by calling: Cinema.Worker.start_link(arg1, arg2, arg3)
      # worker(Cinema.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Cinema.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    CinemaWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/cinema/repo.ex
defmodule Cinema.Repo do
  use Ecto.Repo, otp_app: :cinema

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/cinema/video.ex
defmodule Cinema.Video do
  use Ecto.Schema
  import Ecto.Changeset

  alias Cinema.Repo


  schema "video" do
    field :duration, :float
    field :filename, :string

    timestamps()
  end

  @doc false
  def changeset(video, attrs \\ %{}) do
    video
    |> cast(attrs, [:filename, :duration])
    |> validate_required([:filename])
  end

  def create(attrs) do
    Repo.insert(attrs)
  end

  def get(video_id) do
    Repo.get(Cinema.Video, video_id)
  end

  def get_list do
    Repo.all(Cinema.Video)
  end
end

lib/cinema_web/controllers/page_controller.ex
defmodule CinemaWeb.PageController do
    use CinemaWeb, :controller
  
    def index(conn, _params) do
      render conn, "index.html"
    end
  end
  

lib/cinema_web/controllers/video_api_controller.ex
defmodule CinemaWeb.VideoAPIController do
    use CinemaWeb, :controller
  
    alias Cinema.Video
  
    def show(conn, %{"id" => id}) do
        video = Video.get(id)

        json conn, %{id: video.id, filename: video.filename, inserted_at: video.inserted_at}
    end
  end
  

lib/cinema_web/controllers/video_controller.ex
defmodule CinemaWeb.VideoController do
  use CinemaWeb, :controller

  alias Cinema.Video

  def index(conn, _params) do
    videos = Video.get_list()
    render conn, "index.html", videos: videos
  end

  def new(conn, _params) do
      changeset = Video.changeset(%Video{})
      render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"video" => video_params}) do
      Video.create(Video.changeset(%Video{}, %{filename: video_params["video"].filename}))

      render conn, "index.html"
  end
end

lib/cinema_web/views/cinema_view.ex
defmodule CinemaWeb.VideoView do
  use CinemaWeb, :view
end

lib/cinema_web/views/error_view.ex
defmodule CinemaWeb.ErrorView do
  use CinemaWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/cinema_web/views/layout_view.ex
defmodule CinemaWeb.LayoutView do
  use CinemaWeb, :view
end

lib/cinema_web/views/page_view.ex
defmodule CinemaWeb.PageView do
    use CinemaWeb, :view
  end
  

lib/cinema_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Cinema!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Cinecitta</a>
    </nav>
    <div class="container">
        

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/cinema_web/templates/page/index.html.eex
hello world

lib/cinema_web/templates/video/index.html.eex
<ul>
<%= for video <- @videos do %> 
    <li>
        Created <%= video.filename %> on <%= video.inserted_at %>
    </li>
<% end %>
</ul>
<%= link("Create a video", to: video_path(@conn, :new)) %>

lib/cinema_web/templates/video/new.html.eex
<%= form_for @changeset, video_path(@conn, :create), [multipart: true], fn f -> %>
    <div class="form-group">
        <label>Video</label>
        <%= file_input f, :video, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= submit "Submit", class: "btn btn-primary" %>
    </div>
<% end %>